"""Tool definitions in OpenAI function calling format."""

from __future__ import annotations


def _tool(name: str, description: str, properties: dict, required: list[str] | None = None) -> dict:
    """Helper to create an OpenAI function-calling tool schema."""
    return {
        "type": "function",
        "function": {
            "name": name,
            "description": description,
            "parameters": {
                "type": "object",
                "properties": properties,
                "required": required or [],
            },
        },
    }


def get_tool_definitions() -> list[dict]:
    """Return all tool definitions in OpenAI function calling format."""
    return [
        _tool(
            "list_agents",
            "List native Ares specialist roles, capabilities, tool boundaries, mutation status, timeouts, and iteration budgets.",
            {},
        ),
        _tool(
            "delegate_task",
            "Delegate one bounded specialist task. Use only when specialization provides meaningful value; the root Ares agent remains responsible for the final answer.",
            {
                "agent": {"type": "string", "description": "Specialist role returned by list_agents."},
                "task": {"type": "string", "description": "Specific, independently verifiable assignment."},
                "context": {"type": "string", "description": "Minimal task-specific context; do not duplicate the whole conversation."},
                "timeout_seconds": {"type": "number", "description": "Optional bounded timeout."},
                "required": {"type": "boolean", "default": True},
                "result_format": {"type": "string", "default": "text", "description": "text, markdown, or json."},
            },
            ["agent", "task"],
        ),
        _tool(
            "delegate_tasks_parallel",
            "Run multiple native specialists in dependency-aware parallel waves. Independent tasks overlap; dependent tasks wait for prerequisite results.",
            {
                "tasks": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "task_id": {"type": "string"},
                            "agent": {"type": "string"},
                            "prompt": {"type": "string"},
                            "depends_on": {"type": "array", "items": {"type": "string"}},
                            "context": {"type": "object"},
                            "timeout_seconds": {"type": "number"},
                            "required": {"type": "boolean", "default": True},
                            "result_format": {"type": "string", "default": "text"},
                        },
                        "required": ["task_id", "agent", "prompt"],
                    },
                },
                "context": {"type": "string", "description": "Shared bounded context for every specialist."},
            },
            ["tasks"],
        ),
        _tool(
            "get_agent_run",
            "Inspect a current or completed native multi-agent root or child run.",
            {"run_id": {"type": "string"}},
            ["run_id"],
        ),
        _tool(
            "list_agent_runs",
            "List real native multi-agent manifests for the current session. Agent counts, roles, waves, timing, and status must come from these records, never generated prose.",
            {
                "limit": {"type": "integer", "default": 20, "minimum": 1, "maximum": 100},
                "status": {
                    "type": "string",
                    "enum": ["queued", "running", "succeeded", "failed", "timed_out", "blocked", "cancelled", "interrupted"],
                },
            },
        ),
        _tool(
            "get_latest_agent_run",
            "Get the latest real native multi-agent manifest for the current session, or an explicit zero-agent result when none exists.",
            {},
        ),
        _tool(
            "cancel_agent_run",
            "Cancel an active native multi-agent root run and every unfinished child task.",
            {"run_id": {"type": "string"}},
            ["run_id"],
        ),
        _tool(
            "resume_agent_run",
            "Resume a durable, session-owned read-only agent run from its successful child checkpoints. Unfinished mutation-capable work is never replayed automatically.",
            {"run_id": {"type": "string"}},
            ["run_id"],
        ),
        _tool(
            "store_memory",
            "Save a durable user preference, identity fact, recurring project, or explicit remember-this request. Do not store temporary moods, insults, tool outputs, guesses, current events, or facts about the world.",
            {
                "content": {"type": "string", "description": "Durable user-specific fact to remember, written without guesses or temporary context."},
                "category": {
                    "type": "string",
                    "enum": ["preference", "fact", "belief", "habit", "relationship", "project", "plan", "note"],
                    "description": "Durable memory kind. Time-bounded plans should include expires_at.",
                    "default": "note",
                },
                "confidence": {"type": "number", "default": 1.0},
                "importance": {"type": "number", "minimum": 0, "maximum": 1, "description": "Optional user override; omitted values are calculated automatically."},
                "tags": {"type": "array", "items": {"type": "string"}},
                "source": {"type": "string", "default": "conversation"},
                "source_conversation_id": {"type": "string"},
                "source_message_id": {"type": "string"},
                "valid_from": {"type": "string", "description": "Optional ISO validity start."},
                "expires_at": {"type": "string", "description": "Optional ISO expiration."},
                "supersedes_memory_id": {"type": "integer"},
                "project": {"type": "string"},
                "links": {"type": "object", "description": "Entity links keyed by person, goal, action, file, or project."},
                "merge_mode": {"type": "string", "enum": ["skip", "merge", "store"], "default": "skip"},
                "response_format": {"type": "string", "enum": ["legacy", "structured"], "default": "legacy"},
            },
            ["content"],
        ),
        _tool(
            "search_memory",
            "Search all local recall sources: durable facts, complete saved people records, SQLite conversations, persisted JSONL sessions, and action provenance. Returns exact stored content and stable source IDs.",
            {
                "query": {"type": "string", "description": "What to search for. Empty returns recent local records from selected sources.", "default": ""},
                "limit": {"type": "integer", "default": 12, "description": "Maximum combined results (1-50)."},
                "since": {"type": "string", "description": "Optional ISO or relative lower bound such as yesterday or 5 days ago."},
                "sources": {
                    "type": "array",
                    "items": {"type": "string", "enum": ["facts", "people", "conversations", "sessions", "actions"]},
                    "description": "Optional sources to search. Defaults to all local recall sources.",
                },
                "mode": {"type": "string", "enum": ["relevant", "timeline", "related", "contradictions", "changes", "task_context"], "default": "relevant"},
                "memory_id": {"type": "integer", "description": "Required by related, contradictions, and changes modes."},
                "task": {"type": "string", "description": "Task text for task_context mode."},
                "category": {"type": "string"},
                "tags": {"type": "array", "items": {"type": "string"}},
                "min_confidence": {"type": "number", "minimum": 0, "maximum": 1},
                "min_importance": {"type": "number", "minimum": 0, "maximum": 1},
                "person": {"type": "string"},
                "goal": {"type": "string"},
                "action": {"type": "string"},
                "file": {"type": "string"},
                "project": {"type": "string"},
                "source": {"type": "string"},
                "date_from": {"type": "string"},
                "date_to": {"type": "string"},
                "include_outdated": {"type": "boolean", "default": False},
                "response_format": {"type": "string", "enum": ["legacy", "structured"], "default": "legacy"},
            },
        ),
        _tool(
            "update_memory",
            "Correct or enrich an existing stored memory when the user updates a durable preference or an old memory is wrong.",
            {
                "fact_id": {"type": "integer", "description": "Memory ID."},
                "content": {"type": "string", "description": "Replacement memory text."},
                "category": {"type": "string"},
                "confidence": {"type": "number"},
                "importance": {"type": "number"},
                "mode": {"type": "string", "enum": ["replace", "append", "merge", "outdated"], "default": "replace"},
                "merge_memory_ids": {"type": "array", "items": {"type": "integer"}},
                "tags": {"type": "array", "items": {"type": "string"}},
                "valid_from": {"type": "string"},
                "expires_at": {"type": "string"},
                "project": {"type": "string"},
                "links": {"type": "object"},
                "expected_revision": {"type": "integer"},
                "response_format": {"type": "string", "enum": ["legacy", "structured"], "default": "legacy"},
            },
            ["fact_id"],
        ),
        _tool(
            "delete_memory",
            "Forget a stored memory by ID.",
            {"fact_id": {"type": "integer", "description": "Memory ID to delete."}},
            ["fact_id"],
        ),
        _tool(
            "remember_person",
            "Save a complete local structured record for another person. Search and context return the stored fields exactly as saved.",
            {
                "canonical_name": {"type": "string", "description": "The person's canonical name."},
                "aliases": {"type": "array", "items": {"type": "string"}, "description": "Optional exact names such as mom or Priya aunty."},
                "relation": {"type": "string", "description": "Optional relation such as mom, cousin, or colleague."},
                "phone": {"type": "string", "description": "Optional phone number."},
                "email": {"type": "string", "description": "Optional email address."},
                "important_dates": {"type": "object", "description": "Optional date-label map, for example birthday or anniversary."},
                "notes": {"type": "string", "description": "Optional notes."},
                "source": {"type": "string", "enum": ["manual", "ares-suggested"], "default": "manual"},
                "confidence": {"type": "number", "default": 1.0},
                "pronouns": {"type": "string"},
                "preferred_address": {"type": "string"},
                "timezone": {"type": "string"},
                "communication_preferences": {"type": "object"},
                "preferred_contact_method": {"type": "string", "enum": ["email", "sms", "phone", ""]},
                "organization": {"type": "string"},
                "role": {"type": "string"},
                "interests": {"type": "array", "items": {"type": "string"}},
                "reminder_preferences": {"type": "object"},
                "timeline": {"type": "array", "items": {"type": "object"}},
                "links": {"type": "object", "description": "Entity links keyed by memory, conversation, action, goal, or file."},
                "response_format": {"type": "string", "enum": ["legacy", "structured"], "default": "legacy"},
                "milestones": {"type": "array", "items": {"type": "object"}, "description": "Two to five concrete checkpoints generated for the goal."},
                "next_action": {"type": "string", "description": "The first small, specific action to advance the goal."},
                "blockers": {"type": "array", "items": {"type": "string"}, "description": "Known blockers, if any."},
                "source_conversation_id": {"type": "string", "description": "Optional originating conversation scope."},
            },
            ["canonical_name"],
        ),
        _tool(
            "search_person",
            "Search saved local people by canonical name, exact alias, relation, or note. Returns the full stored record including phone, email, dates, and notes.",
            {
                "query": {"type": "string", "description": "Name, alias, relation, or local note to search."},
                "limit": {"type": "integer", "default": 5},
                "mode": {"type": "string", "enum": ["fuzzy", "relationship", "contact"], "default": "fuzzy"},
                "relation": {"type": "string"},
                "channel": {"type": "string", "enum": ["email", "sms", "phone", ""]},
                "purpose": {"type": "string", "description": "For example SMS, phone call, email invitation, or recent relevance."},
                "include_sensitive": {"type": "boolean", "default": True},
                "response_format": {"type": "string", "enum": ["legacy", "structured"], "default": "legacy"},
            },
            ["query"],
        ),
        _tool(
            "update_person",
            "Update fields on a saved local person record.",
            {
                "person_id": {"type": "integer", "description": "Saved person ID."},
                "canonical_name": {"type": "string"},
                "aliases": {"type": "array", "items": {"type": "string"}},
                "relation": {"type": "string"},
                "phone": {"type": "string", "description": "Pass an empty string to remove a saved phone."},
                "email": {"type": "string", "description": "Pass an empty string to remove a saved email."},
                "important_dates": {"type": "object"},
                "notes": {"type": "string"},
                "source": {"type": "string", "enum": ["manual", "ares-suggested"]},
                "confidence": {"type": "number"},
                "mode": {"type": "string", "enum": ["replace", "aliases", "append_note", "merge"], "default": "replace"},
                "merge_person_id": {"type": "integer", "description": "Duplicate person to merge into person_id."},
                "add_aliases": {"type": "array", "items": {"type": "string"}},
                "remove_aliases": {"type": "array", "items": {"type": "string"}},
                "append_note": {"type": "string"},
                "pronouns": {"type": "string"},
                "preferred_address": {"type": "string"},
                "timezone": {"type": "string"},
                "communication_preferences": {"type": "object"},
                "preferred_contact_method": {"type": "string", "enum": ["email", "sms", "phone", ""]},
                "organization": {"type": "string"},
                "role": {"type": "string"},
                "interests": {"type": "array", "items": {"type": "string"}},
                "reminder_preferences": {"type": "object"},
                "timeline": {"type": "array", "items": {"type": "object"}},
                "links": {"type": "object"},
                "expected_revision": {"type": "integer", "description": "Optional optimistic-concurrency revision."},
                "response_format": {"type": "string", "enum": ["legacy", "structured"], "default": "legacy"},
            },
            ["person_id"],
        ),
        _tool(
            "forget_person",
            "Permanently delete a local person record. Requires confirm=true after the user explicitly approves deletion.",
            {
                "person_id": {"type": "integer", "description": "Saved person ID."},
                "expected_revision": {"type": "integer"},
                "confirm": {"type": "boolean", "default": False},
            },
            ["person_id"],
        ),
        _tool(
            "search_actions",
            "Search the local action and artifact ledger for work Ares already performed. Use for references such as that file, the thing I made, yesterday, or 5 days ago. The ledger stores provenance, never message bodies or other private content.",
            {
                "query": {"type": "string", "default": "", "description": "Optional action, path, tag, or summary search."},
                "since": {"type": "string", "description": "Optional ISO or relative lower bound such as yesterday or 5 days ago."},
                "limit": {"type": "integer", "default": 20},
            },
        ),
        _tool(
            "list_skills",
            "Inspect available reusable skills/playbooks. Use only when the user asks about skills or discovery is necessary; do not narrate skill selection.",
            {
                "category": {"type": "string", "description": "Optional category filter."},
                "query": {"type": "string", "description": "Optional search query."},
            },
        ),
        _tool(
            "load_skill",
            "Internal helper: load a skill's full SKILL.md instructions when needed, then follow it silently to complete the current request.",
            {
                "name": {"type": "string", "description": "Skill name to load."},
            },
            ["name"],
        ),
        _tool(
            "create_skill",
            "Save a reusable workflow as a local Ares skill.",
            {
                "name": {"type": "string", "description": "Skill name in lowercase-hyphen form."},
                "content": {"type": "string", "description": "Full SKILL.md content or markdown body."},
                "category": {"type": "string", "description": "Skill category.", "default": "general"},
            },
            ["name", "content"],
        ),
        _tool(
            "search_skill_marketplace",
            "Read-only search across configured trusted community skill registries. Use when the user explicitly asks to discover or find a skill; never install a result automatically.",
            {
                "query": {"type": "string", "description": "Skill capability to search for."},
                "registry": {"type": "string", "description": "Optional configured registry name."},
            },
            ["query"],
        ),
        _tool(
            "install_marketplace_skill",
            "Download and install an instruction-only skill from a configured registry after the user explicitly asks to install it. The archive is validated; missing MCP dependencies are reported but never auto-added.",
            {
                "slug": {"type": "string", "description": "Registry skill slug."},
                "registry": {"type": "string", "description": "Optional configured registry name."},
                "confirm": {"type": "boolean", "default": False, "description": "Must be true after the user explicitly confirms the requested skill installation."},
            },
            ["slug"],
        ),
        _tool(
            "search_mcp_marketplace",
            "Read-only search across configured trusted MCP registries. Use before suggesting an MCP server; discovery alone never executes or configures a server.",
            {
                "query": {"type": "string", "description": "MCP capability to search for."},
                "registry": {"type": "string", "description": "Optional configured registry name."},
            },
            ["query"],
        ),
        _tool(
            "add_marketplace_mcp",
            "Add a reviewed MCP configuration from a configured trusted registry only after explicit user confirmation. Never call with confirm=true unless the user has approved the exact server plan.",
            {
                "name": {"type": "string", "description": "Registry MCP server name."},
                "registry": {"type": "string", "description": "Optional configured registry name."},
                "confirm": {"type": "boolean", "default": False, "description": "Must be true after the user explicitly approves adding and connecting this MCP server."},
            },
            ["name"],
        ),
        _tool(
            "export_data",
            "Export local Ares data to JSON, with selective profiles and redaction preview. Full exports include saved people and goal records.",
            {
                "path": {"type": "string", "description": "Optional output JSON path."},
                "profile": {
                    "type": "string",
                    "enum": ["full", "memories", "conversations", "config", "actions", "people", "goals"],
                    "default": "full",
                    "description": "Selective export profile.",
                },
            },
        ),
        _tool(
            "web_search",
            "Search the web and automatically read top results. Can prefer the Fetch MCP server when connected, with local fetch_url fallback.",
            {
                "query": {"type": "string", "description": "The web search query."},
                "max_results": {"type": "integer", "default": 5},
                "fetch_top": {
                    "type": "integer",
                    "default": 3,
                    "description": "How many top results to automatically fetch full content for (0 to skip fetching).",
                },
                "max_fetch_chars": {
                    "type": "integer",
                    "default": 8000,
                    "description": "Maximum characters to keep from each fetched page.",
                },
                "fetcher": {
                    "type": "string",
                    "enum": ["auto", "mcp", "local"],
                    "default": "auto",
                    "description": "auto uses Fetch MCP when connected, then local fetch_url. mcp requires Fetch MCP. local uses built-in fetch_url.",
                },
                "provider": {
                    "type": "string",
                    "enum": ["auto", "tavily", "ddgs"],
                    "default": "auto",
                    "description": "Search provider. auto uses Tavily when configured, otherwise ddgs.",
                },
                "domains": {
                    "type": "array",
                    "items": {"type": "string"},
                    "description": "Optional trusted domains to include, for example [\"who.int\", \"nature.com\"].",
                },
                "exclude_domains": {
                    "type": "array",
                    "items": {"type": "string"},
                    "description": "Optional domains to exclude from results.",
                },
                "file_type": {
                    "type": "string",
                    "description": "Optional result file type, such as pdf, docx, xlsx, or csv.",
                },
                "search_mode": {
                    "type": "string",
                    "enum": ["web", "news"],
                    "default": "web",
                    "description": "Use news for recent reporting, web for general research.",
                },
                "recency_days": {
                    "type": "integer",
                    "description": "Optional recency preference in days for news or time-sensitive searches.",
                },
                "cache_ttl_seconds": {
                    "type": "integer",
                    "default": 300,
                    "description": "Reuse an identical recent search for this many seconds (0 disables the cache).",
                },
            },
            ["query"],
        ),
        _tool(
            "fetch_url",
            "Fetch a page/PDF/text URL and extract readable content plus metadata such as final URL, canonical URL, description, status, truncation, and retryability.",
            {
                "url": {"type": "string", "description": "The URL to fetch (must start with http:// or https://)."},
                "max_chars": {
                    "type": "integer",
                    "default": 15000,
                    "description": "Maximum characters to return (default 15000).",
                },
                "extract_text": {
                    "type": "boolean",
                    "default": True,
                    "description": "If true, strips HTML tags and returns plain text. If false, returns raw HTML.",
                },
            },
            ["url"],
        ),
        _tool(
            "download_online_file",
            "Safely download a public online report, PDF, or file into Ares' local research workspace. The downloader blocks local/private network targets, follows only validated redirects, limits size, and returns a file hash.",
            {
                "url": {"type": "string", "description": "Public http(s) URL of the report or file to download."},
                "filename": {"type": "string", "description": "Optional safe local filename override."},
                "max_bytes": {
                    "type": "integer",
                    "default": 20971520,
                    "description": "Maximum download size in bytes (1 MB to 50 MB; default 20 MB).",
                },
            },
            ["url"],
        ),
        _tool(
            "extract_document",
            "Extract readable text and metadata from a local or safely downloaded PDF, Office document, spreadsheet, text file, or archive. Use url for an online source or path for a local file.",
            {
                "path": {"type": "string", "description": "Optional local file path."},
                "url": {"type": "string", "description": "Optional public http(s) URL to download then extract."},
                "filename": {"type": "string", "description": "Optional filename when using url."},
                "max_bytes": {"type": "integer", "default": 20971520, "description": "Maximum document size to extract, up to 25 MB."},
                "max_chars": {"type": "integer", "default": 30000},
            },
        ),
        _tool(
            "create_research_report",
            "Research a question, collect ranked sources and extracted evidence, then save a citation-rich Markdown brief in Ares' local research workspace.",
            {
                "query": {"type": "string", "description": "Research question or topic."},
                "title": {"type": "string", "description": "Optional report title."},
                "max_results": {"type": "integer", "default": 8},
                "fetch_top": {"type": "integer", "default": 5},
                "provider": {"type": "string", "enum": ["auto", "tavily", "ddgs"], "default": "auto"},
                "domains": {"type": "array", "items": {"type": "string"}},
                "exclude_domains": {"type": "array", "items": {"type": "string"}},
                "file_type": {"type": "string"},
                "search_mode": {"type": "string", "enum": ["web", "news"], "default": "web"},
                "recency_days": {"type": "integer"},
            },
            ["query"],
        ),
        _tool(
            "telegram_send_file",
            "Send an existing local file to one explicitly allowlisted Telegram chat. This is an external delivery action and requires confirm=true after the user explicitly asks to send the file.",
            {
                "path": {"type": "string", "description": "Existing local file path to deliver."},
                "chat_id": {"type": "integer", "description": "Optional allowlisted Telegram chat ID. Omit only when exactly one chat is allowlisted."},
                "caption": {"type": "string", "description": "Optional Telegram document caption."},
                "confirm": {"type": "boolean", "description": "Must be true only after the user explicitly confirms this Telegram delivery."},
            },
            ["path", "confirm"],
        ),
        _tool(
            "read_file",
            "Read a local text file with line numbers and automatic nearby imports/classes/functions/heading context for code or markdown slices.",
            {
                "path": {"type": "string", "description": "Absolute, home-relative, or workspace-relative path."},
                "start_line": {"type": "integer", "default": 1},
                "num_lines": {"type": "integer", "default": 200},
                "mode": {"type": "string", "enum": ["lines", "symbol", "heading", "json", "imports", "references", "tests"], "default": "lines"},
                "symbol": {"type": "string"},
                "heading": {"type": "string"},
                "selector": {"type": "string", "description": "Dotted JSON selector."},
                "cursor": {"type": "string"},
                "encoding": {"type": "string", "default": "auto"},
                "max_results": {"type": "integer", "default": 50},
                "response_format": {"type": "string", "enum": ["legacy", "structured"], "default": "legacy"},
            },
            ["path"],
        ),
        _tool(
            "search_files",
            "Search local files by content and/or file name glob pattern using ripgrep when available, ranked results, snippets, and ignore-file awareness.",
            {
                "query": {"type": "string", "description": "Content regex/text to search for.", "default": ""},
                "path": {"type": "string", "description": "Directory to search.", "default": "."},
                "name_pattern": {"type": "string", "description": "Glob pattern such as *.py.", "default": ""},
                "max_results": {"type": "integer", "default": 20},
                "mode": {"type": "string", "enum": ["text", "name", "semantic", "symbol", "references", "imports", "todo", "changed", "date"], "default": "text"},
                "symbol": {"type": "string"},
                "changed_only": {"type": "boolean", "default": False},
                "date_from": {"type": "string"},
                "date_to": {"type": "string"},
                "group_by": {"type": "string", "enum": ["", "file"]},
                "include_related_tests": {"type": "boolean", "default": False},
                "cursor": {"type": "string"},
                "response_format": {"type": "string", "enum": ["legacy", "structured"], "default": "legacy"},
            },
        ),
        _tool(
            "list_directory",
            "List a local directory with file sizes and subdirectories.",
            {
                "path": {"type": "string", "description": "Directory path.", "default": "."},
                "max_items": {"type": "integer", "default": 30},
                "mode": {"type": "string", "enum": ["legacy", "project"], "default": "legacy"},
                "sort": {"type": "string", "enum": ["name", "size", "activity", "relevance"], "default": "name"},
                "query": {"type": "string"},
                "include_git": {"type": "boolean", "default": False},
                "include_summary": {"type": "boolean", "default": False},
                "ignore_generated": {"type": "boolean", "default": True},
                "cursor": {"type": "string"},
                "response_format": {"type": "string", "enum": ["legacy", "structured"], "default": "legacy"},
            },
        ),
        _tool(
            "get_file_info",
            "Get metadata about a file or directory: type, size, timestamps, binary status.",
            {
                "path": {"type": "string", "description": "File or directory path."},
            },
            ["path"],
        ),
        _tool(
            "glob_pattern",
            "Find files matching a glob pattern (e.g. **/*.py, src/**/*.ts).",
            {
                "pattern": {"type": "string", "description": "Glob pattern."},
                "path": {"type": "string", "default": ".", "description": "Directory to search from."},
                "max_results": {"type": "integer", "default": 50, "description": "Max files to return."},
            },
            ["pattern"],
        ),
        _tool(
            "write_file",
            "Create a NEW file or FULLY OVERWRITE an existing one. Dry runs include a patch preview for overwrites. NEVER use for adding/inserting text into an existing file. For adding/inserting: use edit_file (find+replace), insert_line (by line number), append_to_file (end), prepend_to_file (start), or batch_file_ops. If overwriting, confirm=true is required.",
            {
                "path": {"type": "string", "description": "File path to write."},
                "content": {"type": "string", "description": "File content to write."},
                "dry_run": {"type": "boolean", "default": False, "description": "Preview without writing."},
                "confirm": {"type": "boolean", "default": False, "description": "Confirm destructive overwrite."},
                "mode": {"type": "string", "enum": ["overwrite", "append", "merge", "patch", "template"], "default": "overwrite"},
                "patch": {"type": "string"},
                "template": {"type": "string"},
                "variables": {"type": "object"},
                "encoding": {"type": "string", "default": "utf-8"},
                "newline": {"type": "string", "enum": ["preserve", "lf", "crlf"], "default": "preserve"},
                "create_parents": {"type": "boolean", "default": True},
                "formatter": {"type": "string", "enum": ["", "auto", "json"]},
                "validation": {"type": "string", "enum": ["", "auto", "json", "python"]},
                "verify_command": {"type": "string"},
                "response_format": {"type": "string", "enum": ["legacy", "structured"], "default": "legacy"},
            },
            ["path", "content"],
        ),
        _tool(
            "edit_file",
            "Edit a file by searching and replacing text with diff preview, conflict hints, and backup creation. Great for targeted changes without touching the rest of the file. old_text must match uniquely. If no match, returns the closest content as a suggestion.",
            {
                "path": {"type": "string", "description": "File path."},
                "old_text": {"type": "string", "description": "Text to find (must match uniquely in the file)."},
                "new_text": {"type": "string", "description": "Replacement text."},
                "dry_run": {"type": "boolean", "default": False, "description": "Preview without editing."},
                "mode": {"type": "string", "enum": ["replace", "regex", "line_range", "patch", "python_ast", "json_fields"], "default": "replace"},
                "match_index": {"type": "integer", "default": 1},
                "pattern": {"type": "string"},
                "replacement": {"type": "string"},
                "count": {"type": "integer", "default": 0},
                "start_line": {"type": "integer"},
                "end_line": {"type": "integer"},
                "patch": {"type": "string"},
                "symbol": {"type": "string"},
                "fields": {"type": "object"},
                "encoding": {"type": "string", "default": "utf-8"},
                "formatter": {"type": "string", "enum": ["", "auto", "json"]},
                "validation": {"type": "string", "enum": ["", "auto", "json", "python"]},
                "verify_command": {"type": "string"},
                "response_format": {"type": "string", "enum": ["legacy", "structured"], "default": "legacy"},
            },
            ["path"],
        ),
        _tool(
            "create_directory",
            "Create a directory and any missing parent directories (mkdir -p).",
            {
                "path": {"type": "string", "description": "Directory path to create."},
                "dry_run": {"type": "boolean", "default": False, "description": "Preview without creating."},
            },
            ["path"],
        ),
        _tool(
            "delete_file",
            "Delete a file or empty directory. Always requires confirm=true.",
            {
                "path": {"type": "string", "description": "File or directory path to delete."},
                "confirm": {"type": "boolean", "default": False, "description": "Confirm deletion."},
                "dry_run": {"type": "boolean", "default": False, "description": "Preview without deleting."},
            },
            ["path"],
        ),
        _tool(
            "move_file",
            "Move or rename a file or directory. Creates parent directories of destination as needed.",
            {
                "source": {"type": "string", "description": "Current file path."},
                "destination": {"type": "string", "description": "New file path."},
                "confirm": {"type": "boolean", "default": False, "description": "Confirm if destination exists."},
                "dry_run": {"type": "boolean", "default": False, "description": "Preview without moving."},
            },
            ["source", "destination"],
        ),

        _tool(
            "batch_edit",
            "Execute multiple file operations transactionally with rollback on partial failure. Supports write, edit, delete, move, copy, and mkdir/create_directory actions with per-operation results.",
            {
                "operations": {
                    "type": "array",
                    "description": "List of operations. Each operation has action plus fields for that action.",
                    "items": {"type": "object"},
                },
                "dry_run": {"type": "boolean", "default": False, "description": "Preview all operations without changing files."},
                "confirm": {"type": "boolean", "default": False, "description": "Confirm destructive operations and overwrites."},
                "max_operations": {"type": "integer", "default": 100, "description": "Maximum operations to execute (1-500)."},
                "mode": {"type": "string", "enum": ["execute", "plan"], "default": "execute"},
                "rollback_on_failure": {"type": "boolean", "default": True},
                "verification": {"type": "array", "items": {"type": "string"}},
                "response_format": {"type": "string", "enum": ["legacy", "structured"], "default": "legacy"},
            },
            ["operations"],
        ),
        _tool(
            "glob_apply",
            "Apply a safe bulk action to files matching a glob pattern. Defaults to dry_run=true. Supports list, delete, move, and copy.",
            {
                "pattern": {"type": "string", "description": "Glob pattern such as *.tmp or **/*.log."},
                "action": {"type": "string", "enum": ["list", "delete", "move", "copy"], "default": "list"},
                "path": {"type": "string", "default": ".", "description": "Root directory to search from."},
                "destination": {"type": "string", "description": "Destination directory for move/copy actions."},
                "replacement": {"type": "string", "description": "Optional destination file name template using {name}, {stem}, {suffix}."},
                "dry_run": {"type": "boolean", "default": True, "description": "Preview matching operations without changing files."},
                "confirm": {"type": "boolean", "default": False, "description": "Required for destructive glob actions when dry_run=false."},
                "max_matches": {"type": "integer", "default": 100, "description": "Maximum matches to act on (1-500)."},
            },
            ["pattern"],
        ),
        _tool(
            "show_file_with_line_numbers",
            "Show a text file with stable 1-based line numbers before line-based edits.",
            {
                "path": {"type": "string", "description": "File path."},
                "start": {"type": "integer", "description": "Optional first line to show."},
                "end": {"type": "integer", "description": "Optional last line to show."},
            },
            ["path"],
        ),
        _tool(
            "insert_line",
            "Insert text before or after a 1-based line number. Makes an automatic backup before editing and supports dry_run diff preview.",
            {
                "path": {"type": "string"},
                "line": {"type": "integer"},
                "text": {"type": "string"},
                "position": {"type": "string", "enum": ["before", "after"], "default": "after"},
                "dry_run": {"type": "boolean", "default": False},
                "confirm_dangerous": {"type": "boolean", "default": False},
            },
            ["path", "line", "text"],
        ),
        _tool(
            "replace_lines",
            "Replace an inclusive 1-based line range. Makes an automatic backup before editing and supports dry_run diff preview.",
            {
                "path": {"type": "string"},
                "start": {"type": "integer"},
                "end": {"type": "integer"},
                "new_text": {"type": "string"},
                "dry_run": {"type": "boolean", "default": False},
                "confirm_dangerous": {"type": "boolean", "default": False},
            },
            ["path", "start", "end", "new_text"],
        ),
        _tool(
            "delete_lines",
            "Delete an inclusive 1-based line range. Makes an automatic backup before editing and supports dry_run diff preview.",
            {
                "path": {"type": "string"},
                "start": {"type": "integer"},
                "end": {"type": "integer"},
                "dry_run": {"type": "boolean", "default": False},
                "confirm_dangerous": {"type": "boolean", "default": False},
            },
            ["path", "start", "end"],
        ),
        _tool(
            "preview_diff",
            "Preview a unified diff for replacing a file with new_content without changing the file.",
            {"path": {"type": "string"}, "new_content": {"type": "string"}},
            ["path", "new_content"],
        ),
        _tool(
            "backup_file",
            "Create a named timestamped .ares_backups restore point and backup index entry for a file.",
            {"path": {"type": "string"}, "label": {"type": "string", "default": ""}},
            ["path"],
        ),
        _tool(
            "undo_last_edit",
            "Restore the newest backup for a file from its .ares_backups folder.",
            {"path": {"type": "string"}, "dry_run": {"type": "boolean", "default": False}},
            ["path"],
        ),
        _tool(
            "batch_file_ops",
            "Run line-based file operations atomically with rollback if any operation fails. Supports insert_line, replace_lines, delete_lines, append, and prepend.",
            {
                "ops": {"type": "array", "items": {"type": "object"}},
                "dry_run": {"type": "boolean", "default": False},
                "confirm_dangerous": {"type": "boolean", "default": False},
                "max_operations": {"type": "integer", "default": 100},
            },
            ["ops"],
        ),
        _tool(
            "find_text",
            "Find text in one file and return matching line numbers with nearby context.",
            {
                "path": {"type": "string"},
                "query": {"type": "string"},
                "context": {"type": "integer", "default": 2},
                "max_results": {"type": "integer", "default": 20},
            },
            ["path", "query"],
        ),
        _tool(
            "append_to_file",
            "Append text to a file with backup, diff preview, and dry_run support.",
            {"path": {"type": "string"}, "text": {"type": "string"}, "dry_run": {"type": "boolean", "default": False}, "confirm_dangerous": {"type": "boolean", "default": False}},
            ["path", "text"],
        ),
        _tool(
            "prepend_to_file",
            "Prepend text to a file with backup, diff preview, and dry_run support.",
            {"path": {"type": "string"}, "text": {"type": "string"}, "dry_run": {"type": "boolean", "default": False}, "confirm_dangerous": {"type": "boolean", "default": False}},
            ["path", "text"],
        ),
        _tool(
            "compare_files",
            "Compare two text files and return a unified diff.",
            {"left": {"type": "string"}, "right": {"type": "string"}},
            ["left", "right"],
        ),
        _tool(
            "create_file_from_template",
            "Create a new file from a built-in template: python, html, readme, notes, school_essay, or homework.",
            {
                "path": {"type": "string"},
                "template": {"type": "string", "default": "notes"},
                "dry_run": {"type": "boolean", "default": False},
                "confirm": {"type": "boolean", "default": False},
                "confirm_dangerous": {"type": "boolean", "default": False},
            },
            ["path"],
        ),
        _tool(
            "safe_path_status",
            "Check whether a file path is considered safe or blocked as a dangerous system path.",
            {"path": {"type": "string"}},
            ["path"],
        ),

        _tool(
            "disk_usage",
            "Show disk usage for a directory tree with sizes and file counts (like du -sh).",
            {
                "path": {"type": "string", "description": "Directory to analyze.", "default": "."},
                "max_depth": {"type": "integer", "default": 2, "description": "How deep to traverse (1-5)."},
            },
        ),
        _tool(
            "checksum",
            "Compute file checksum hash (md5, sha1, sha256, sha512). Useful for verifying file integrity.",
            {
                "path": {"type": "string", "description": "File path."},
                "algorithm": {"type": "string", "default": "sha256", "description": "Hash algorithm: md5, sha1, sha256, or sha512."},
            },
            ["path"],
        ),
        _tool(
            "copy_file",
            "Copy a file to a new location.",
            {
                "source": {"type": "string", "description": "Source file path."},
                "destination": {"type": "string", "description": "Destination file path."},
                "overwrite": {"type": "boolean", "default": False, "description": "Overwrite if destination exists."},
                "dry_run": {"type": "boolean", "default": False, "description": "Preview without copying."},
            },
            ["source", "destination"],
        ),
        _tool(
            "find_duplicates",
            "Find duplicate files by size and content hash. Useful for cleaning up redundant files.",
            {
                "path": {"type": "string", "description": "Directory to scan.", "default": "."},
                "min_size": {"type": "integer", "default": 1024, "description": "Minimum file size to check (bytes)."},
                "max_results": {"type": "integer", "default": 50, "description": "Max duplicate groups to show."},
            },
        ),
        _tool(
            "tail_file",
            "Read the last N lines of a file (like Unix tail).",
            {
                "path": {"type": "string", "description": "File path."},
                "num_lines": {"type": "integer", "default": 20, "description": "Number of lines to read from end."},
            },
            ["path"],
        ),
        _tool(
            "head_file",
            "Read the first N lines of a file (like Unix head).",
            {
                "path": {"type": "string", "description": "File path."},
                "num_lines": {"type": "integer", "default": 20, "description": "Number of lines to read."},
            },
            ["path"],
        ),
        _tool(
            "count_lines",
            "Count lines in files with optional content and name filtering (like wc -l).",
            {
                "path": {"type": "string", "description": "Directory to scan.", "default": "."},
                "pattern": {"type": "string", "default": "", "description": "Content regex pattern to match lines."},
                "name_pattern": {"type": "string", "default": "", "description": "File name glob pattern (e.g. *.py)."},
            },
        ),
        _tool(
            "file_tree",
            "Display directory tree structure (like the tree command).",
            {
                "path": {"type": "string", "description": "Directory path.", "default": "."},
                "max_depth": {"type": "integer", "default": 3, "description": "Max depth to show (1-10)."},
                "show_files": {"type": "boolean", "default": True, "description": "Show files (false = dirs only)."},
                "mode": {"type": "string", "enum": ["legacy", "project"], "default": "legacy"},
                "sort": {"type": "string", "enum": ["name", "size", "activity", "relevance"], "default": "name"},
                "query": {"type": "string"},
                "max_items": {"type": "integer", "default": 100},
                "include_git": {"type": "boolean", "default": False},
                "include_summary": {"type": "boolean", "default": True},
                "ignore_generated": {"type": "boolean", "default": True},
                "cursor": {"type": "string"},
                "response_format": {"type": "string", "enum": ["legacy", "structured"], "default": "legacy"},
            },
        ),
        _tool(
            "run_code",
            "Execute Python code in the pinned persistent Python runtime session. Full access to stdlib, pip, filesystem, network. Supports reset checkpoints and dependency fingerprints.",
            {
                "code": {"type": "string", "description": "Python code to execute"},
                "timeout": {"type": "integer", "description": "Max seconds before kill (1-300, default 30)"},
                "cwd": {"type": "string", "description": "Working directory (default: home)"},
                "reset": {"type": "boolean", "default": False, "description": "Reset the pinned Python runtime before executing."},
                "include_fingerprint": {"type": "boolean", "default": False, "description": "Include a dependency fingerprint in the result."},
                "mode": {"type": "string", "enum": ["execute", "history", "variables", "packages", "checkpoint", "rollback", "reset"], "default": "execute"},
                "session_id": {"type": "string", "default": "default"},
                "cell_name": {"type": "string"},
                "checkpoint_id": {"type": "string"},
                "capture_artifacts": {"type": "boolean", "default": True},
                "response_format": {"type": "string", "enum": ["legacy", "structured"], "default": "legacy"},
            },
        ),
        _tool(
            "run_command",
            "Execute a shell command (bash, git, npm, python, docker, etc.) in the pinned persistent shell session. Supports command profiles, timeout hints, structured summaries, pipes, redirects, && chaining. DO NOT use for phone operations — use phone_status, phone_get_notifications, phone_send_sms, phone_call_number, or phone_search_contact instead.",
            {
                "command": {"type": "string", "description": "Shell command to execute, or @key from the project command registry."},
                "command_key": {"type": "string", "description": "Optional key from [tool.ares.commands] or npm:<script>."},
                "timeout": {"type": "integer", "description": "Max seconds before kill (1-300, default 30)"},
                "cwd": {"type": "string", "description": "Working directory"},
                "profile": {"type": "string", "enum": ["quick", "test", "build", "long"], "description": "Optional timeout profile."},
                "reset": {"type": "boolean", "default": False, "description": "Reset the pinned shell runtime before executing."},
                "include_fingerprint": {"type": "boolean", "default": False, "description": "Include a dependency fingerprint in the result."},
                "mode": {"type": "string", "enum": ["execute", "start", "inspect", "attach", "follow", "stop", "stdin", "jobs", "history", "discover", "git_summary", "checkpoint"], "default": "execute"},
                "session_id": {"type": "string", "default": "default"},
                "job_id": {"type": "string"},
                "stdin": {"type": "string"},
                "detach": {"type": "boolean", "default": False},
                "tail_chars": {"type": "integer", "default": 100000},
                "retry": {"type": "integer", "minimum": 0, "maximum": 3, "default": 0},
                "checkpoint_id": {"type": "string"},
                "response_format": {"type": "string", "enum": ["legacy", "structured"], "default": "legacy"},
            },
        ),
        _tool(
            "run_project_check",
            "Run one named project verification check pre-configured by the repository owner. This accepts only the check name; it cannot execute arbitrary shell text, use pipes, redirects, nested interpreters, or network commands.",
            {
                "check": {"type": "string", "description": "Configured [tool.ares.agent_checks] name."},
                "cwd": {"type": "string", "description": "Assigned builder workspace."},
                "timeout_seconds": {"type": "integer", "description": "Maximum seconds (1-300, default 180)."},
            },
            required=["check"],
        ),
        _tool(
            "generate_image",
            "Generate an image from a text prompt using Pollinations.ai (free, no API key). Returns saved file path and records an asset manifest row with dimensions, format, checksum, and generation history.",
            {
                "prompt": {"type": "string", "description": "Text description of the image to generate"},
                "width": {"type": "integer", "description": "Output width in pixels (default 1024)"},
                "height": {"type": "integer", "description": "Output height in pixels (default 1024)"},
                "model": {"type": "string", "enum": ["flux", "turbo", "stable-diffusion"], "description": "Model to use (default flux)"},
                "seed": {"type": "integer", "description": "Deterministic seed for reproducibility"},
            },
            required=["prompt"],
        ),
        _tool(
            "image_info",
            "Get metadata about an image: dimensions, format, mode, file size, EXIF data.",
            {
                "path": {"type": "string", "description": "Path to the image file"},
            },
            required=["path"],
        ),
        _tool(
            "resize_image",
            "Resize an image preserving aspect ratio. Uses LANCZOS resampling and records an asset manifest row with dimensions, format, checksum, and transformation history.",
            {
                "path": {"type": "string", "description": "Source image path"},
                "width": {"type": "integer", "description": "Target width (scales proportionally)"},
                "height": {"type": "integer", "description": "Target height (scales proportionally)"},
                "percent": {"type": "integer", "description": "Scale by percentage (50 = half)"},
                "output": {"type": "string", "description": "Output path (default: overwrite source)"},
            },
            required=["path"],
        ),
        _tool(
            "convert_image",
            "Convert image between formats (PNG, JPEG, WebP, BMP, GIF). Handles RGBA to JPEG transparency and records an asset manifest row.",
            {
                "path": {"type": "string", "description": "Source image path"},
                "format": {"type": "string", "enum": ["png", "jpeg", "webp", "bmp", "gif"], "description": "Target format"},
                "output": {"type": "string", "description": "Output path (default: same name, new extension)"},
                "quality": {"type": "integer", "description": "JPEG/WebP quality 1-100 (default 85)"},
            },
            required=["path", "format"],
        ),
        _tool(
            "crop_image",
            "Crop a rectangular region from an image. Coordinates in pixels, right/bottom exclusive. Records an asset manifest row.",
            {
                "path": {"type": "string", "description": "Source image path"},
                "left": {"type": "integer", "description": "Left edge in pixels (default 0)"},
                "top": {"type": "integer", "description": "Top edge in pixels (default 0)"},
                "right": {"type": "integer", "description": "Right edge in pixels (exclusive)"},
                "bottom": {"type": "integer", "description": "Bottom edge in pixels (exclusive)"},
                "output": {"type": "string", "description": "Output path (default: overwrite source)"},
            },
            required=["path", "right", "bottom"],
        ),
        _tool(
            "terminal_exec",
            "Execute a shell command with full output capture, and optionally display it in the interactive terminal panel. Use this when the user explicitly says 'run in terminal', 'show me in the terminal', or wants to see the command in the terminal panel. For normal command execution without visual terminal, use run_command instead.",
            {
                "command": {"type": "string", "description": "Shell command to execute, or @key from the project command registry."},
                "command_key": {"type": "string", "description": "Optional key from [tool.ares.commands] or npm:<script>."},
                "wait": {"type": "boolean", "description": "Wait for command to complete (default true)"},
                "timeout": {"type": "integer", "description": "Max seconds to wait for completion (default 30)"},
                "cwd": {"type": "string", "description": "Working directory for the command"},
                "profile": {"type": "string", "enum": ["quick", "test", "build", "long"], "description": "Optional timeout profile."},
                "mode": {"type": "string", "enum": ["execute", "start", "inspect", "attach", "follow", "stop", "stdin", "jobs", "history"], "default": "execute"},
                "session_id": {"type": "string", "default": "terminal"},
                "job_id": {"type": "string"},
                "stdin": {"type": "string"},
                "signal": {"type": "string"},
                "rows": {"type": "integer"},
                "columns": {"type": "integer"},
                "tail_chars": {"type": "integer", "default": 100000},
                "response_format": {"type": "string", "enum": ["legacy", "structured"], "default": "legacy"},
            },
        ),

        _tool(
            "create_cron_job",
            "Create a recurring scheduled job that runs a fresh Ares agent session.",
            {"name": {"type": "string"}, "prompt": {"type": "string"}, "cron": {"type": "string", "description": "Five-field cron expression or supported natural phrase."}, "timezone": {"type": "string", "default": "UTC"}, "enabled": {"type": "boolean", "default": True}, "max_iterations": {"type": "integer"}},
            ["name", "prompt", "cron"],
        ),
        _tool("list_cron_jobs", "List scheduled cron jobs and their status.", {"include_disabled": {"type": "boolean", "default": True}}),
        _tool("get_cron_job", "Get details for a scheduled cron job.", {"job_id": {"type": "string"}}, ["job_id"]),
        _tool("update_cron_job", "Update a scheduled cron job fields.", {"job_id": {"type": "string"}, "name": {"type": "string"}, "prompt": {"type": "string"}, "cron": {"type": "string"}, "timezone": {"type": "string"}, "enabled": {"type": "boolean"}, "state": {"type": "string"}, "max_iterations": {"type": "integer"}}, ["job_id"]),
        _tool("delete_cron_job", "Delete a cron job while retaining logs.", {"job_id": {"type": "string"}}, ["job_id"]),
        _tool("run_cron_job_now", "Trigger a cron job immediately.", {"job_id": {"type": "string"}}, ["job_id"]),
        _tool("get_cron_logs", "Read recent markdown logs for a cron job.", {"job_id": {"type": "string"}, "limit": {"type": "integer", "default": 5}}, ["job_id"]),
        _tool(
            "get_watcher_capabilities",
            "Discover every Ares watcher source, authenticated-browser preset, safety policy, and currently connected MCP integration tool before designing a custom watcher.",
            {},
        ),
        _tool(
            "create_watcher",
            "Create a durable Ares-native watcher. Use browser with preset=instagram_dm for authenticated DM monitoring, tool/tool_name for any read-only Ares integration, website for pages, custom for JSON APIs, or instagram for the Meta Graph API.",
            {
                "name": {"type": "string", "description": "Human-readable watcher name."},
                "type": {"type": "string", "enum": ["website", "custom", "instagram", "browser", "tool"], "default": "website"},
                "url": {"type": "string", "description": "Target URL; optional for tool workflows and current-tab browser snapshots."},
                "preset": {"type": "string", "enum": ["instagram_dm", "browser_page"], "description": "Optional authenticated browser recipe."},
                "tool_name": {"type": "string", "description": "One existing local or MCP tool to observe repeatedly; creates a one-step tool workflow."},
                "arguments": {"type": "object", "description": "Arguments for tool_name."},
                "config": {"type": "object", "description": "Extraction, detection, workflow steps, thresholds, ignore patterns, and notification overrides."},
                "interval_seconds": {"type": "integer", "minimum": 20, "default": 900},
                "ai_action": {"type": "string", "enum": ["notify", "suggest", "auto"], "default": "notify"},
                "ai_prompt": {"type": "string"},
                "enabled": {"type": "boolean", "default": True},
                "goal_id": {"type": "integer", "description": "Optional existing goal to link after creation; watcher creation is rolled back if linking fails."},
            },
            ["name"],
        ),
        _tool("list_watchers", "List and search the complete Ares watcher fleet with status, cadence, errors, and counters.", {"query": {"type": "string"}, "enabled_only": {"type": "boolean", "default": False}, "limit": {"type": "integer", "default": 100}}),
        _tool("get_watcher", "Get one watcher plus its latest captured signal, incidents, and recent check telemetry.", {"watcher_id": {"type": "string"}}, ["watcher_id"]),
        _tool(
            "update_watcher",
            "Reconfigure an existing watcher without losing its history.",
            {"watcher_id": {"type": "string"}, "name": {"type": "string"}, "url": {"type": "string"}, "config": {"type": "object"}, "interval_seconds": {"type": "integer", "minimum": 20}, "ai_action": {"type": "string", "enum": ["notify", "suggest", "auto"]}, "ai_prompt": {"type": "string"}, "enabled": {"type": "boolean"}},
            ["watcher_id"],
        ),
        _tool("pause_watcher", "Pause a watcher while preserving its configuration and history.", {"watcher_id": {"type": "string"}}, ["watcher_id"]),
        _tool("resume_watcher", "Resume a paused watcher and make it due on the next scheduler tick.", {"watcher_id": {"type": "string"}}, ["watcher_id"]),
        _tool("run_watcher_now", "Run a watcher immediately through the active Ares runtime and return the captured status or detected change.", {"watcher_id": {"type": "string"}}, ["watcher_id"]),
        _tool("list_watcher_events", "Query watcher incidents across the fleet or for one watcher.", {"watcher_id": {"type": "string"}, "severity": {"type": "string", "enum": ["info", "warning", "critical"]}, "unacknowledged_only": {"type": "boolean", "default": False}, "limit": {"type": "integer", "default": 100}}),
        _tool("acknowledge_watcher_event", "Acknowledge one watcher incident after it has been reviewed.", {"event_id": {"type": "string"}}, ["event_id"]),
        _tool("get_watcher_overview", "Get fleet health, success rate, incident counts, latency, and recent watcher throughput.", {}),
        _tool("delete_watcher", "Permanently delete one watcher and its full history. Set confirm=true only after explicit user approval.", {"watcher_id": {"type": "string"}, "confirm": {"type": "boolean", "default": False}}, ["watcher_id"]),
        _tool(
            "create_task",
            "Create a durable ordered workflow task. Each plan step must name one tool and its arguments; the guarded runner executes safe/reversible steps automatically and pauses before consequential steps.",
            {
                "goal": {"type": "string", "description": "Human-readable workflow goal."},
                "plan": {"type": "array", "items": {"type": "object"}, "description": "Ordered explicit steps: step_id, tool_name, arguments, optional description, and optional verify object."},
                "related_person_ids": {"type": "array", "items": {"type": "integer"}, "description": "Optional saved people relevant to this task."},
                "session_id": {"type": "string", "description": "Optional originating session id."},
            },
            ["goal", "plan"],
        ),
        _tool("list_tasks", "List durable workflow tasks and their current status.", {"statuses": {"type": "array", "items": {"type": "string"}}, "limit": {"type": "integer", "default": 20}}),
        _tool("get_task_status", "Get the status and safe step summary for one durable workflow task.", {"task_id": {"type": "string"}}, ["task_id"]),
        _tool(
            "update_task",
            "Update a pending/failed workflow goal or plan, or retry a failed task. Running and confirmation-paused tasks must be cancelled before editing.",
            {
                "task_id": {"type": "string"},
                "goal": {"type": "string"},
                "plan": {"type": "array", "items": {"type": "object"}},
                "related_person_ids": {"type": "array", "items": {"type": "integer"}},
                "session_id": {"type": "string"},
                "expected_revision": {"type": "integer"},
                "retry": {"type": "boolean", "default": False},
            },
            ["task_id"],
        ),
        _tool("cancel_task", "Cancel a durable workflow task and revoke any active run lease.", {"task_id": {"type": "string"}, "expected_revision": {"type": "integer"}}, ["task_id"]),
        _tool(
            "run_task",
            "Run or resume a durable workflow through the guarded runner. If it pauses, review its consolidated consequential-step request; set confirm=true only after the user explicitly approves that exact request.",
            {
                "task_id": {"type": "string"},
                "confirm": {"type": "boolean", "default": False, "description": "Only true after explicit approval of the task's pending confirmation request."},
                "max_steps": {"type": "integer", "default": 25, "description": "Safety cap for steps run in this invocation."},
            },
            ["task_id"],
        ),
        _tool(
            "create_goal",
            "Create a durable user goal only after the user has clearly named the outcome they want. Goals describe what/why; use create_task separately for execution steps.",
            {
                "title": {"type": "string", "description": "Concise outcome-oriented goal title."},
                "description": {"type": "string"},
                "category": {"type": "string", "default": "general"},
                "priority": {"type": "string", "enum": ["low", "normal", "high"], "default": "normal"},
                "target_date": {"type": "string", "description": "Optional ISO date YYYY-MM-DD."},
                "parent_goal_id": {"type": "integer", "description": "Optional parent goal for multi-level decomposition."},
                "source": {"type": "string", "enum": ["manual", "ares-suggested"], "default": "manual"},
                "confidence": {"type": "number", "default": 1.0},
            },
            ["title"],
        ),
        _tool(
            "update_goal",
            "Update editable goal fields with optional optimistic revision protection. A manual progress update becomes the authoritative progress value until the next explicit sync.",
            {
                "goal_id": {"type": "integer"}, "title": {"type": "string"}, "description": {"type": "string"},
                "status": {"type": "string", "enum": ["active", "paused", "completed", "abandoned"]},
                "category": {"type": "string"}, "priority": {"type": "string", "enum": ["low", "normal", "high"]},
                "progress_percent": {"type": "integer", "minimum": 0, "maximum": 100},
                "target_date": {"anyOf": [{"type": "string"}, {"type": "null"}]},
                "parent_goal_id": {"anyOf": [{"type": "integer"}, {"type": "null"}]},
                "next_action": {"type": "string"},
                "expected_revision": {"type": "integer"},
                "resolves_signal_id": {"type": "integer", "description": "Optional linked watcher signal to acknowledge in the same transaction as this update."},
            },
            ["goal_id"],
        ),
        _tool(
            "list_goals",
            "List or search durable goals, optionally including due-soon and overdue groups.",
            {
                "statuses": {"type": "array", "items": {"type": "string", "enum": ["active", "paused", "completed", "abandoned"]}},
                "category": {"type": "string"}, "query": {"type": "string"},
                "limit": {"type": "integer", "default": 50}, "include_due": {"type": "boolean", "default": False},
                "within_days": {"type": "integer", "default": 7},
            },
        ),
        _tool("get_goal_status", "Get one goal with its recursive child tree, task/action/watcher links, pending watcher signals, revision, due state, and progress timeline.", {"goal_id": {"type": "integer"}, "timeline_limit": {"type": "integer", "default": 20}, "include_resolved_signals": {"type": "boolean", "default": False}}, ["goal_id"]),
        _tool("complete_goal", "Mark a goal completed only when the user confirms completion. Sets progress to 100 and can atomically resolve the watcher signal that prompted the confirmation.", {"goal_id": {"type": "integer"}, "expected_revision": {"type": "integer"}, "resolves_signal_id": {"type": "integer"}}, ["goal_id"]),
        _tool("pause_goal", "Pause an active goal without deleting its history or links.", {"goal_id": {"type": "integer"}, "expected_revision": {"type": "integer"}}, ["goal_id"]),
        _tool("abandon_goal", "Mark a goal abandoned while preserving its history and evidence.", {"goal_id": {"type": "integer"}, "expected_revision": {"type": "integer"}}, ["goal_id"]),
        _tool(
            "decompose_goal",
            "Create independently completable child goals beneath a larger goal. Multi-level goal trees are supported.",
            {"goal_id": {"type": "integer"}, "subgoals": {"type": "array", "items": {"type": "object", "properties": {"title": {"type": "string"}, "description": {"type": "string"}, "category": {"type": "string"}, "priority": {"type": "string", "enum": ["low", "normal", "high"]}, "target_date": {"type": "string"}}, "required": ["title"]}}},
            ["goal_id", "subgoals"],
        ),
        _tool("link_goal_task", "Link an existing durable workflow task to the goal it advances, providing evidence for explicit progress synchronization.", {"goal_id": {"type": "integer"}, "task_id": {"type": "string"}}, ["goal_id", "task_id"]),
        _tool("link_goal_action", "Link an existing Action Ledger record to a goal as completed historical evidence.", {"goal_id": {"type": "integer"}, "action_id": {"type": "integer"}}, ["goal_id", "action_id"]),
        _tool("link_goal_watcher", "Link an existing proactive watcher to a goal. Future watcher incidents become reviewable evidence and never change goal state automatically.", {"goal_id": {"type": "integer"}, "watcher_id": {"type": "string"}}, ["goal_id", "watcher_id"]),
        _tool("unlink_goal_watcher", "Stop a watcher from producing new evidence for a goal without deleting either record or prior signals.", {"goal_id": {"type": "integer"}, "watcher_id": {"type": "string"}}, ["goal_id", "watcher_id"]),
        _tool("get_goal_signals", "List pending or historical watcher signals linked to goals, including source event, severity, anti-nag surfaces, snooze, and resolution state.", {"goal_id": {"type": "integer"}, "include_acknowledged": {"type": "boolean", "default": False}, "include_snoozed": {"type": "boolean", "default": True}, "limit": {"type": "integer", "default": 100}}),
        _tool("acknowledge_goal_signal", "Dismiss or mark a linked watcher signal reviewed without changing the goal. Also reconciles the source watcher incident after every linked goal signal is resolved.", {"signal_id": {"type": "integer"}, "resolution": {"type": "string", "enum": ["dismissed", "reviewed"], "default": "reviewed"}, "note": {"type": "string"}}, ["signal_id"]),
        _tool("snooze_goal_signal", "Temporarily hide a pending watcher signal from automatic goal context while preserving it for explicit inspection.", {"signal_id": {"type": "integer"}, "hours": {"type": "integer", "minimum": 1, "maximum": 8760, "default": 24}, "until": {"type": "string", "description": "Optional ISO timestamp overriding hours."}, "note": {"type": "string"}}, ["signal_id"]),
        _tool("sync_goal_progress", "Explicitly derive goal progress from completed child goals, linked completed tasks, and linked action evidence. Never runs silently.", {"goal_id": {"type": "integer"}}, ["goal_id"]),
        _tool(
            "record_goal_progress",
            "Add a durable timestamped goal check-in note, optionally updating its manual progress percentage.",
            {"goal_id": {"type": "integer"}, "note": {"type": "string"}, "progress_percent": {"type": "integer", "minimum": 0, "maximum": 100}, "expected_revision": {"type": "integer"}},
            ["goal_id", "note"],
        ),
        _tool("delete_goal", "Permanently delete a goal and its links/timeline. Requires explicit user approval and confirm=true; child goals are preserved and detached.", {"goal_id": {"type": "integer"}, "expected_revision": {"type": "integer"}, "confirm": {"type": "boolean", "default": False}}, ["goal_id"]),
        _tool(
            "list_follow_ups",
            "List bounded open follow-ups, including their IDs, status, schedule, confidence, and provenance.",
            {"limit": {"type": "integer", "minimum": 1, "maximum": 100, "default": 20}},
        ),
        _tool(
            "snooze_follow_up",
            "Snooze an open follow-up until a future time. A naive ISO timestamp is interpreted in the configured local timezone.",
            {
                "follow_up_id": {"type": "string"},
                "hours": {"type": "integer", "minimum": 1, "maximum": 8760, "default": 24},
                "until": {"type": "string", "description": "Optional timezone-aware ISO timestamp, or local naive ISO timestamp."},
            },
            ["follow_up_id"],
        ),
        _tool(
            "dismiss_follow_up",
            "Dismiss an open follow-up without marking its underlying outcome complete.",
            {"follow_up_id": {"type": "string"}, "reason": {"type": "string"}},
            ["follow_up_id"],
        ),
        _tool(
            "resolve_follow_up",
            "Resolve or cancel an open follow-up when the user confirms the outcome or cancellation.",
            {
                "follow_up_id": {"type": "string"},
                "status": {"type": "string", "enum": ["resolved", "cancelled"], "default": "resolved"},
                "resolution": {"type": "string"},
            },
            ["follow_up_id"],
        ),
        _tool(
            "phone_status",
            "PHONE TOOL — the ONLY way to check Android phone status. Do NOT use run_command with kdeconnect-cli or adb for this. Checks KDE Connect and ADB bridge health. No arguments.",
            {},
        ),
        _tool(
            "phone_get_notifications",
            "PHONE TOOL — the ONLY way to read Android notifications. Do NOT use run_command with kdeconnect-cli for this. Read a live snapshot of recent Android notifications via KDE Connect. Treat output as private, transient data.",
            {"limit": {"type": "integer", "default": 20, "description": "Maximum notifications to return."}},
        ),
        _tool(
            "phone_search_contact",
            "PHONE TOOL — the ONLY way to search contacts. Do NOT use run_command with kdeconnect-cli for this. Search Android contacts synced through KDE Connect by name or number.",
            {"query": {"type": "string", "description": "Name or phone number to search for."}},
            ["query"],
        ),
        _tool(
            "phone_send_sms",
            "PHONE TOOL — the ONLY way to send SMS. Do NOT use run_command with kdeconnect-cli for this. Send a real SMS text message through the paired Android phone via KDE Connect. Use only when the user explicitly asks to text this recipient.",
            {
                "number": {"type": "string", "description": "Recipient phone number or one exact explicitly saved person alias such as mom."},
                "message": {"type": "string", "description": "SMS body to send."},
            },
            ["number", "message"],
        ),
        _tool(
            "phone_call_number",
            "PHONE TOOL — the ONLY way to make phone calls. Do NOT use run_command with adb for this. Place a real phone call through ADB. Never call unless the user has just explicitly asked for this exact call; confirm=true is required.",
            {
                "number": {"type": "string", "description": "Phone number or one exact explicitly saved person alias to call."},
                "confirm": {"type": "boolean", "default": False, "description": "Must be true after explicit user approval for this exact call."},
            },
            ["number"],
        ),
        _tool(
            "phone_launch_app",
            "PHONE TOOL — the ONLY way to open an app on the phone. Do NOT use run_command with adb for this. Pass the Android package name (e.g. com.google.android.youtube, com.whatsapp, com.instagram.android).",
            {"package": {"type": "string", "description": "Android package name of the app to launch (e.g. com.google.android.youtube)."}},
            ["package"],
        ),
        _tool(
            "phone_open_url",
            "PHONE TOOL — the ONLY way to open a URL on the phone. Do NOT use run_command with adb for this. Opens the URL in the default browser or matching app.",
            {"url": {"type": "string", "description": "URL to open on the phone (e.g. https://youtube.com)."}},
            ["url"],
        ),
        _tool("telephony_status", "Inspect provider-backed telephone configuration, active calls, and media bridge readiness.", {}),
        _tool(
            "telephony_call",
            "Place an outbound Twilio telephone call to an exact saved telephony contact or number. Unknown raw numbers require confirm=true after the user approves the exact number.",
            {
                "recipient": {"type": "string", "description": "Saved telephony contact name/nickname or an E.164 phone number."},
                "confirm": {"type": "boolean", "default": False, "description": "Required for an unknown raw number after explicit approval."},
            },
            ["recipient"],
        ),
        _tool("telephony_answer", "Mark an incoming telephony session answered after the provider/media bridge has connected.", {"call_id": {"type": "string"}}, ["call_id"]),
        _tool("telephony_hangup", "End an active provider-backed phone call and finalize its local transcript and summary.", {"call_id": {"type": "string"}}, ["call_id"]),
        _tool("telephony_mute", "Set local/provider mute state for an active call when the configured media bridge supports it.", {"call_id": {"type": "string"}, "muted": {"type": "boolean", "default": True}}, ["call_id"]),
        _tool("telephony_get_call", "Read one local phone-call transcript, status, summary, and duration by call ID.", {"call_id": {"type": "string"}}, ["call_id"]),
        _tool("telephony_list_calls", "List recent locally persisted provider-backed phone calls.", {"limit": {"type": "integer", "default": 20}}),
        _tool("telephony_list_contacts", "List encrypted local telephony contacts after decrypting them for this local request.", {"limit": {"type": "integer", "default": 100}}),
        _tool(
            "telephony_save_contact",
            "Save or update an encrypted local telephony contact used for provider-backed calls.",
            {"name": {"type": "string"}, "phone_number": {"type": "string"}, "nickname": {"type": "string"}, "notes": {"type": "string"}},
            ["name", "phone_number"],
        ),
        _tool("telephony_transfer", "Transfer an active provider-backed call through the configured Twilio routing endpoint.", {"call_id": {"type": "string"}, "destination": {"type": "string"}}, ["call_id", "destination"]),
        _tool(
            "update_config",
            "Surgically update a single config field in ~/.ares/config.json. Reads the existing config first, updates ONLY the specified path, and writes back. Never overwrites other fields. Use dot notation for nested fields (e.g. 'phone.enabled', 'model').",
            {
                "path": {"type": "string", "description": "Dot-notation config path to update (e.g. 'phone.enabled', 'model', 'voice.enabled')."},
                "value": {"description": "New value for the field. Use native types: true/false for booleans, numbers for ints, strings for text, arrays for lists."},
            },
            ["path", "value"],
        ),
        _tool(
            "get_current_datetime",
            "Get the current date and time. Returns datetime, date, time, timezone, day of week, and unix timestamp.",
            {
                "timezone": {
                    "type": "string",
                    "description": "Optional IANA timezone (e.g. 'America/New_York'). Defaults to system timezone.",
                },
            },
        ),
    ]
