"use client";

import { Code2, Globe2, HeartPulse, Save, Send, Settings2, Sparkles, UserRound } from "lucide-react";
import { useState } from "react";
import type { WorkspaceSettings } from "@/lib/types";

interface Props {
  settings: WorkspaceSettings;
  save: (settings: WorkspaceSettings & { advanced_mode?: boolean }) => void;
  saving: boolean;
  activeTab?: string;
  embedded?: boolean;
}
type Section = keyof WorkspaceSettings;

const tabs = [
  { id: "general", label: "General", icon: Settings2 },
  { id: "identity", label: "Identity", icon: UserRound },
  { id: "personalization", label: "Personalization", icon: Sparkles },
  { id: "telegram", label: "Telegram", icon: Send },
  { id: "browser", label: "Browser & tools", icon: Globe2 },
  { id: "monitoring", label: "Monitoring", icon: HeartPulse },
  { id: "advanced", label: "Advanced", icon: Code2 },
];

function Field({ label, hint, children, wide = false }: { label: string; hint?: string; children: React.ReactNode; wide?: boolean }) {
  return <div className={`field ${wide ? "span-2" : ""}`}><label>{label}</label>{children}{hint && <p className="field-hint">{hint}</p>}</div>;
}

function Toggle({ label, copy, checked, onChange }: { label: string; copy: string; checked: boolean; onChange: (value: boolean) => void }) {
  return <div className="toggle-row"><div className="toggle-copy"><strong>{label}</strong><small>{copy}</small></div><label className="switch"><input type="checkbox" checked={checked} onChange={event => onChange(event.target.checked)} /><i /></label></div>;
}

function asString(value: unknown) { return value === undefined || value === null ? "" : String(value); }
function asBoolean(value: unknown) { return Boolean(value); }
function asNumber(value: unknown, fallback = 0) { const number = Number(value); return Number.isFinite(number) ? number : fallback; }

export function SettingsView({ settings, save, saving, activeTab, embedded = false }: Props) {
  const [internalTab, setInternalTab] = useState("general");
  const tab = activeTab || internalTab;
  const [draft, setDraft] = useState<WorkspaceSettings>(settings);
  const [advancedMode, setAdvancedMode] = useState(false);
  const section = (name: Section) => (draft[name] || {}) as Record<string, unknown>;
  const update = (name: Section, key: string, value: unknown) => setDraft(current => ({ ...current, [name]: { ...(current[name] || {}), [key]: value } }));
  const model = section("model"); const identity = section("identity"); const personal = section("personalization");
  const telegram = section("telegram"); const browser = section("browser"); const monitoring = section("monitoring");
  const workspace = section("workspace"); const advanced = section("advanced");

  return <section className={embedded ? "settings-config" : "view is-active"}><div className={`settings-shell ${embedded ? "is-embedded" : ""}`}>
    {!embedded && <aside className="settings-nav"><div><p className="eyebrow">CONTROL SURFACE</p><h1>Settings</h1></div>{tabs.map(item => <button className={tab === item.id ? "is-active" : ""} key={item.id} onClick={() => setInternalTab(item.id)}><item.icon />{item.label}</button>)}</aside>}
    <div className="settings-content"><form onSubmit={event => { event.preventDefault(); save({ ...draft, advanced_mode: advancedMode }); }}>
      {tab === "general" && <div className="settings-panel is-active"><div className="settings-heading"><h2>General runtime</h2><p>Choose the model and local workspace behavior. Model changes apply immediately; host changes take effect after restart.</p></div>
        <div className="settings-group"><div className="settings-group-head"><strong>Model gateway</strong><small>Shared by the console, CLI, Telegram, voice, and watchers.</small></div><div className="field-grid"><Field label="Model"><input value={asString(model.name)} onChange={event => update("model", "name", event.target.value)} placeholder="deepseek-v4-flash-free" /></Field><Field label="API base URL"><input value={asString(model.api_base_url)} onChange={event => update("model", "api_base_url", event.target.value)} placeholder="https://…/v1" /></Field><Field label="API key" hint={asBoolean(model.api_key_configured) ? "A key is already configured. Leave blank to preserve it." : "Stored in your local shared Ares config."}><input type="password" value={asString(model.api_key)} onChange={event => update("model", "api_key", event.target.value)} placeholder={asBoolean(model.api_key_configured) ? "••••••••••••" : "Paste API key"} autoComplete="off" /></Field><Field label="Maximum agent iterations"><input type="number" min={1} max={500} value={asNumber(model.agent_max_iterations, 80)} onChange={event => update("model", "agent_max_iterations", Number(event.target.value))} /></Field></div></div>
        <div className="settings-group"><div className="settings-group-head"><strong>Separate workspace host</strong><small>This operator console stays independent from the Ares marketing site.</small></div><div className="field-grid"><Field label="Bind host"><input value={asString(workspace.host)} onChange={event => update("workspace", "host", event.target.value)} /></Field><Field label="Port"><input type="number" min={1} max={65535} value={asNumber(workspace.port, 8766)} onChange={event => update("workspace", "port", Number(event.target.value))} /></Field></div><Toggle label="Serve power workspace" copy="Launch this Next.js console with the unified Ares runtime." checked={asBoolean(workspace.enabled)} onChange={value => update("workspace", "enabled", value)} /></div>
      </div>}

      {tab === "identity" && <div className="settings-panel is-active"><div className="settings-heading"><h2>Your operating context</h2><p>Ares uses this local profile to understand who it is helping, how you work, and what matters now.</p></div><div className="settings-group"><div className="settings-group-head"><strong>Identity & preferences</strong><small>Structured into your user-owned profile.md.</small></div><div className="field-grid"><Field label="Your name"><input value={asString(identity.user_name)} onChange={event => update("identity", "user_name", event.target.value)} /></Field><Field label="Pronouns"><input value={asString(identity.pronouns)} onChange={event => update("identity", "pronouns", event.target.value)} /></Field><Field label="Coding style"><input value={asString(identity.coding_style)} onChange={event => update("identity", "coding_style", event.target.value)} /></Field><Field label="Assistant response style"><input value={asString(identity.assistant_style)} onChange={event => update("identity", "assistant_style", event.target.value)} /></Field><Field label="Terminal / OS" wide><input value={asString(identity.terminal)} onChange={event => update("identity", "terminal", event.target.value)} /></Field><Field label="Current projects" wide><textarea value={asString(identity.projects)} onChange={event => update("identity", "projects", event.target.value)} placeholder="One project per line" /></Field><Field label="Goals" wide><textarea value={asString(identity.goals)} onChange={event => update("identity", "goals", event.target.value)} placeholder="One goal per line" /></Field><Field label="Notes" wide><textarea value={asString(identity.notes)} onChange={event => update("identity", "notes", event.target.value)} /></Field></div></div></div>}

      {tab === "personalization" && <div className="settings-panel is-active"><div className="settings-heading"><h2>Personalization</h2><p>Define Ares as a collaborator: identity, communication contract, values, and durable custom instructions.</p></div><div className="settings-group"><div className="settings-group-head"><strong>Assistant identity</strong><small>Saved to your user-owned soul.md and injected into every Ares surface.</small></div><div className="field-grid one"><Field label="Assistant name"><input value={asString(personal.assistant_name)} onChange={event => update("personalization", "assistant_name", event.target.value)} /></Field><Field label="Personality"><textarea value={asString(personal.personality)} onChange={event => update("personalization", "personality", event.target.value)} placeholder="One trait per line" /></Field><Field label="Communication style"><textarea value={asString(personal.communication_style)} onChange={event => update("personalization", "communication_style", event.target.value)} /></Field><Field label="Values"><textarea value={asString(personal.values)} onChange={event => update("personalization", "values", event.target.value)} /></Field><Field label="Custom instructions"><textarea value={asString(personal.custom_instructions)} onChange={event => update("personalization", "custom_instructions", event.target.value)} placeholder="Long-lived rules Ares should follow" /></Field></div></div></div>}

      {tab === "telegram" && <div className="settings-panel is-active"><div className="settings-heading"><h2>Telegram channel</h2><p>Operate the same Ares agent from Telegram with a strict local allowlist and shared conversations, tools, skills, and watchers.</p></div><div className="settings-group"><Toggle label="Enable Telegram" copy="Start polling your bot when the unified runtime launches." checked={asBoolean(telegram.enabled)} onChange={value => update("telegram", "enabled", value)} /><Toggle label="Allow group chats" copy="Disabled is safer. Authorized private chat IDs continue to work." checked={asBoolean(telegram.allow_group_chats)} onChange={value => update("telegram", "allow_group_chats", value)} /><Toggle label="Show tool progress" copy="Post compact tool and watcher activity while Ares works." checked={asBoolean(telegram.show_tool_progress)} onChange={value => update("telegram", "show_tool_progress", value)} /><Toggle label="Transcribe voice messages" copy="Use configured local or Sarvam speech-to-text for incoming audio." checked={asBoolean(telegram.audio_transcription_enabled)} onChange={value => update("telegram", "audio_transcription_enabled", value)} /></div><div className="settings-group"><div className="settings-group-head"><strong>Bot credentials & authorization</strong><small>Get a bot token from @BotFather, then authorize only chats you control.</small></div><div className="field-grid"><Field label="Bot token" hint={asBoolean(telegram.bot_token_configured) ? "A token is configured. Blank preserves it." : "Required before enabling Telegram."} wide><input type="password" value={asString(telegram.bot_token)} onChange={event => update("telegram", "bot_token", event.target.value)} placeholder={asBoolean(telegram.bot_token_configured) ? "••••••••••••" : "123456:ABC…"} autoComplete="off" /></Field><Field label="Allowed chat IDs" hint="Comma-separated numeric IDs. Unknown chats are denied." wide><input value={Array.isArray(telegram.allowed_chat_ids) ? telegram.allowed_chat_ids.join(", ") : asString(telegram.allowed_chat_ids)} onChange={event => update("telegram", "allowed_chat_ids", event.target.value)} placeholder="123456789, 987654321" /></Field></div></div></div>}

      {tab === "browser" && <div className="settings-panel is-active"><div className="settings-heading"><h2>Browser &amp; tool runtime</h2><p>Choose how Playwright connects. Browser-backed watchers use this same authenticated capability.</p></div><div className="settings-group"><div className="settings-group-head"><strong>Playwright operating mode</strong><small>Changing mode rebuilds and reconnects the Playwright MCP server.</small></div><div className="field-grid"><Field label="Browser mode"><select value={asString(browser.mode || "auto")} onChange={event => update("browser", "mode", event.target.value)}><option value="auto">Auto select</option><option value="isolated">Isolated Ares profile</option><option value="system">System Chrome via CDP</option><option value="extension">Connected browser extension</option></select></Field><Field label="Chrome DevTools port"><input type="number" min={1} max={65535} value={asNumber(browser.cdp_port, 9222)} onChange={event => update("browser", "cdp_port", Number(event.target.value))} /></Field><Field label="Chrome executable path" wide><input value={asString(browser.chrome_path)} onChange={event => update("browser", "chrome_path", event.target.value)} placeholder="Auto-detect when blank" /></Field><Field label="Extension token" hint={asBoolean(browser.extension_token_configured) ? "Token configured; blank preserves it." : "Only required for extension mode."} wide><input type="password" value={asString(browser.extension_token)} onChange={event => update("browser", "extension_token", event.target.value)} autoComplete="off" /></Field></div></div></div>}

      {tab === "monitoring" && <div className="settings-panel is-active"><div className="settings-heading"><h2>Monitoring runtime</h2><p>Tune fleet scheduling, concurrency, tool-backed observation, and the dedicated advanced watcher console.</p></div><div className="settings-group"><Toggle label="Enable watcher runtime" copy="Start the scheduler, incident pipeline, and notification dispatcher with Ares." checked={asBoolean(monitoring.enabled)} onChange={value => update("monitoring", "enabled", value)} /><Toggle label="Enable tool & browser watchers" copy="Let watchers use bounded read-only Ares and MCP tool workflows." checked={asBoolean(monitoring.tool_monitors_enabled)} onChange={value => update("monitoring", "tool_monitors_enabled", value)} /><Toggle label="Allow mutating tool steps" copy="Expert-only global opt-in; each watcher still needs its own explicit opt-in." checked={asBoolean(monitoring.allow_mutating_tool_steps)} onChange={value => update("monitoring", "allow_mutating_tool_steps", value)} /><Toggle label="Serve advanced watcher console" copy="Keep the detailed standalone watcher UI available for deep incident work." checked={asBoolean(monitoring.dashboard_enabled)} onChange={value => update("monitoring", "dashboard_enabled", value)} /></div><div className="settings-group"><div className="settings-group-head"><strong>Scheduler parameters</strong><small>Defaults apply to new watchers; existing watcher cadence remains unchanged.</small></div><div className="field-grid"><Field label="Scheduler poll seconds"><input type="number" min={0.5} max={300} step={0.5} value={asNumber(monitoring.poll_seconds, 5)} onChange={event => update("monitoring", "poll_seconds", Number(event.target.value))} /></Field><Field label="Max concurrent checks"><input type="number" min={1} max={100} value={asNumber(monitoring.max_concurrency, 8)} onChange={event => update("monitoring", "max_concurrency", Number(event.target.value))} /></Field><Field label="Default interval seconds"><input type="number" min={20} value={asNumber(monitoring.default_interval_seconds, 900)} onChange={event => update("monitoring", "default_interval_seconds", Number(event.target.value))} /></Field><Field label="Default AI action"><select value={asString(monitoring.default_ai_action || "notify")} onChange={event => update("monitoring", "default_ai_action", event.target.value)}><option value="notify">Notify</option><option value="suggest">Suggest response</option><option value="auto">Automatic action</option></select></Field><Field label="Dashboard host"><input value={asString(monitoring.dashboard_host)} onChange={event => update("monitoring", "dashboard_host", event.target.value)} /></Field><Field label="Dashboard port"><input type="number" min={1} max={65535} value={asNumber(monitoring.dashboard_port, 8080)} onChange={event => update("monitoring", "dashboard_port", Number(event.target.value))} /></Field></div></div></div>}

      {tab === "advanced" && <div className="settings-panel is-active"><div className="settings-heading"><h2>Raw personalization files</h2><p>Power-user escape hatch. Enable raw mode only when you want these editors to replace the structured Identity and Personalization forms.</p></div><div className="settings-group"><Toggle label="Save raw files on submit" copy="When enabled, profile.md and soul.md below become authoritative." checked={advancedMode} onChange={setAdvancedMode} /><div className="field-grid one"><Field label="profile.md"><textarea className="code-field" value={asString(advanced.profile)} onChange={event => update("advanced", "profile", event.target.value)} spellCheck={false} /></Field><Field label="soul.md"><textarea className="code-field" value={asString(advanced.soul)} onChange={event => update("advanced", "soul", event.target.value)} spellCheck={false} /></Field></div></div></div>}

      <div className="settings-savebar"><span>Changes are saved to shared local Ares configuration.</span><button type="submit" className="primary-btn" disabled={saving}><Save />{saving ? "Saving…" : "Save changes"}</button></div>
    </form></div>
  </div></section>;
}
